set_unless[:eclipse][:user] = "dvberkel"
set_unless[:eclipse][:group] = "dvberkel"
set_unless[:eclipse][:bin] = "/home/dvberkel/bin/"
set_unless[:eclipse][:download] = "/home/dvberkel/Downloads/"
set_unless[:eclipse][:url] = "http://eclipse.mirror.triple-it.nl/technology/epp/downloads/release/kepler/SR1/"
set_unless[:eclipse][:package] = "eclipse-cpp-kepler-SR1-linux-gtk-x86_64.tar.gz"
set_unless[:eclipse][:package_name] = "eclipse-kepler"
